// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:48fb86f8-fec9-4773-8169-4ef85d6a6442",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_d79JKtmxD",
    "aws_user_pools_web_client_id": "1m6g40qhm6leb2valkjqptpjvh",
    "aws_cloud_logic_custom": [
        {
            "name": "api5ff476c6",
            "endpoint": "https://nnqquz0b0g.execute-api.us-west-2.amazonaws.com/Prod",
            "region": "us-west-2"
        }
    ],
    "aws_content_delivery_bucket": "awsreact2-20181208090149--hostingbucket",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "https://d2n7dro28zgw7o.cloudfront.net",
    "aws_dynamodb_all_tables_region": "us-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "applisting",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
